---
title: "R Exercises"
author: "Mauro Diaz"
format: html
editor: visual
execute:
  echo: true
  warning: true
  error: true
---

## Exercise 1.9
```{r}
set.seed(1)

cards <- 1:52 # creates a vector with the element 1 to 52
n     <- 10000 # number of samples

# SINTAXIS: vector is used for creating empy vectors of a specific type (mode)
q4    <- vector(mode = "logical", length = n)
q2    <- vector(mode = "logical", length = n)

for (i in 1:n) {
  p1      <- sample(cards, 26) # sample of 26 elements in the vector of the cards
  q4[i]   <- sum(1:4 %in% p1) == 4 # sum of the elements 1 to 4 that are present in the sample
  q2[i]   <- sum(1:4 %in% p1) >= 2
}
sum(q4) / n # sum(q4) sums the elements in TRUE.
sum(q2) / n
```
## Exercise 1.10
Fair die: $\Omega = \{ 1, \dots, 6\}$ and $A = \{3, 4, 5, 6\}$, $B = \{1, 2, 3\}$ for the lower bound and $A = B + {4}$ for the upper bound
```{r}
set.seed(1)

n      <- 10000
a_l <- 3:6
a_u <- 1:4
b <- 1:3

samples <- sample(1:6, n, replace = TRUE)

lb     <- vector(mode = "logical", length = n)
ub     <- vector(mode = "logical", length = n)

for (i in 1:n) {
  lb[i] <- samples[i] %in% a_l & samples[i] %in% b
  ub[i] <- samples[i] %in% a_u & samples[i] %in% b
}
sum(lb) / n
sum(ub) / n
```
## Exercise 2.8
```{r}
set.seed(1)

n <- 1000
# Generate 1000 numbers from the Omega_1 space uniformly
unif_s <- runif(n)

# for every number, calculate the mapping with f
die_s  <- ceiling(6 * unif_s)

# as.factor converts the elements in categories and summary counts the number of elem in each category
summary(as.factor(die_s)) / n
```

